language: python

python: 2.7

env:

    - TOX_ENV=py27-django17
    - TOX_ENV=py27-django18
    - TOX_ENV=py27-django19
    - TOX_ENV=py34-django18
    - TOX_ENV=py34-django19
    - TOX_ENV=py35-django18
    - TOX_ENV=py35-django19

install: pip install codecov tox

script: tox -e $TOX_ENV

after_success:
    - codecov -e $TOX_ENV
